### PR TITLE
Switch GLM to a submodule, instead of being included directly

### LINKED ISSUE #61: Depend on GLM through a git submodule
Why add more cruft to the code base?  Instead of having to update GLM manually, you can just set the submodule to point to a more recent commit.

### PR DESCRIPTION
**Pull request by JesseTG**
Fix #61 

No need to update it manually any more, just do `git submodule foreach git pull`, and then push when you want to update `glm` to the latest commit.  It's even in the same directory, so nothing about `gli`'s usage of `glm` has changed; all you have to do is just clone it the first time with `git clone --recursive`.

### CODE REVIEW

**Comment by Armada651** [comment]
:+1: Submodules were made for this stuff. The submodule will pin a certain commit, so there's no downside compared to doing it manually.

**Comment by JesseTG** [comment]
Any thoughts on this (or the other #66) PR?

**Comment by Groovounet** [comment]
Also submodule is a strong value for people actually developing GLI, it's a big step back for people just using GLI. Many people will just download GLI clicking on "download ZIP" in Github to try it out. These people expect that it works out of the box / zip but it will not because Github doesn't include the source of the submodules when clicking that button.

**Comment by JesseTG** [comment]
Shouldn't they be cloning the git repo anyway?  This *is* GitHub.

**Comment by Armada651** [comment]
@JesseTG As much as I love submodules, the "Download Zip" issue is a valid reason. This is a issue GitHub really should be fixing ASAP.

**Comment by JesseTG** [comment]
Hm, okay.  Is there a public issue tracker that would be an appropriate place to file that?

**Pull request closed without merging**
