### PR TITLE
Multiple swizzle format fixes

### PR DESCRIPTION
**Pull request by ousnius**
- added A to "FORMAT_RGBA_BP_UNORM_BLOCK16" and "FORMAT_RGBA_BP_SRGB_BLOCK16"
- removed A from "FORMAT_RGB_ETC2_SRGB_BLOCK8"
- removed G, B and A from "FORMAT_R_EAC_UNORM_BLOCK8" and "FORMAT_R_EAC_SNORM_BLOCK8"
- removed B and A from "FORMAT_RG_EAC_UNORM_BLOCK16" and "FORMAT_RG_EAC_SNORM_BLOCK16"

### CODE REVIEW

**Comment by ousnius** [comment]
My commit message has "removed A from RGBA..." in it, but it should be "added A to RGBA...".

**Comment by Xottab-DUTY** [comment]
You can change the commit description by `git commit --amend`

**Comment by ousnius** [comment]
Fixes #122

**Comment by Groovounet** [comment]
Thanks for contributing,
Christophe

**Pull request merged**
