### PR TITLE
DXT1 decompression and sampling

### PR DESCRIPTION
**Pull request by amc522**

### CODE REVIEW

**Comment by Groovounet** [comment]
This looks like interesting work but I really need to study it through. Also, unit tests seem necessary.

**Comment by amc522** [comment]
Cool, I'll add in some unit test code. Also need to modify it to support 3d textures. Just read through some docs that say all the block compression schemes are supported with 3d textures on modern cards.

**Comment by amc522** [comment]
@Groovounet Added some testing for decompressing dxt1 blocks.

**Comment by amc522** [comment]
@Groovounet Just wondering if there was anything further you wanted me to modify with the code? Or if it's not something you wish to add to the project, just say the word and I'll close the request.

**Comment by Groovounet** [comment]
I just merged your PR, thanks for contributing!
Christophe

**Comment by amc522** [comment]
Sweet! I'll have a pull request with BC2 (DXT3), BC3 (DXT5), BC4, and BC5 coming in the next week.

**Comment by Groovounet** [comment]
Great, looking forward to it!

**Pull request merged**
