### PR TITLE
dx: Fix ALPHAPIXELS flags being specified for formats without alpha channels

### PR DESCRIPTION
**Pull request by Armada651**
The `DDPF_ALPHAPIXELS` flags was inverted for some formats. This PR fixes that inversion, but also removes the RGB formats of DXT1 for DDS textures because the test texture `kueken7_rgba_dxt1`, like all other DDS DXT1 textures, does not specify the `DDPF_ALPHAPIXELS` flag in its header.

Note that some textures always specify `DDPF_ALPHAPIXELS` and differentiate between formats that have alpha channels based on the explicit format.

### Why remove DXT1 RGB for DDS textures in favor of the RGBA format?

Because DDS has no way to differentiate between the two formats. The reason DXT1 does not specify the alpha channel in its header is because the alpha channel can be enabled per-block in the texture as specified on MSDN.

> If 64-bit blocks - that is, format DXT1 - are used for the texture, it is possible to mix the opaque and 1-bit alpha formats on a per-block basis within the same texture.

This mix of opaque and alpha blocks is done using the color compare function `color_0 > color_1`. There is no part of the MSDN specification that defines an RGB format that ignores the alpha channel in alpha blocks.

Source: https://msdn.microsoft.com/en-us/library/windows/desktop/bb204843%28v=vs.85%29.aspx

### What's the difference between the two formats?

According to the [OpenGL spec](https://www.opengl.org/registry/specs/EXT/texture_compression_s3tc.txt) they are functionally the same except for the following:

        The alpha component for a texel at location (x,y) in the block is
        given by:

            0.0,               if color0 <= color1 and code(x,y) == 3
            1.0,               otherwise

So the **only** difference is that the RGB format does not set the alpha component, even when the DXT1 format as specified on MSDN implies that it should.

### Doesn't the [MSDN specification](https://msdn.microsoft.com/en-us/library/windows/desktop/bb206238%28v=vs.85%29.aspx) specify a format for DXT1 that ignores the color compare?

This refers to this quote:

> The color compare used in DXT1 to determine if the texel is transparent is not used with these formats. It is assumed that without the color compare the color data is always treated as if in 4-color mode.

No, because this sentence is used in the context of DXT4 and DXT5 which don't use the color compare. Even if you take it out of the context, the RGB format in OpenGL still uses the color compare, so it still would not be correct to use the RGB format.

The color compare that allows you to turn the alpha-bit on per-block is always used for DXT1. The specifications prove it as it goes on to say:

> In other words, the if statement at the top of the DXT1 code should be:

```
if ((color_0 > color_1) OR !DXT1) {
```

### Doesn't the [EXT_texture_compression_s3tc spec](https://www.opengl.org/registry/specs/EXT/texture_compression_s3tc.txt) for DXT1 specify the reason for the RGB enum?

[The OpenGL wiki seems to refer](https://www.opengl.org/wiki/S3_Texture_Compression#DXT1_with_1-bit_Alpha) to this quote in the spec as the purpose of the RGB enum:

        (5) Is the encoding of the RGB components for DXT1 formats correct in this
        spec?  MSDN documentation does not specify an RGB color for the
        "transparent" encoding.  Is it really black?

        RESOLVED:  Yes.  The specification for the DXT1 format initially
        required black, but later changed that requirement to a
        recommendation.  All vendors involved in the definition of this
        specification support black.  In addition, specifying black has a
        useful behavior.

        When blending multiple texels (GL_LINEAR filtering), mixing opaque and
        transparent samples is problematic.  Defining a black color on
        transparent texels achieves a sensible result that works like a
        texture with premultiplied alpha.  For example, if three opaque white
        and one transparent sample is being averaged, the result would be a
        75% intensity gray (with an alpha of 75%).  This is the same result on
        the color channels as would be obtained using a white color, 75%
        alpha, and a SRC_ALPHA blend factor.

What is explained in this part of the quote is not the reason for the existence of the RGB format. What is explained here is the reason for the pre-multiplication of the alpha value, resulting in the color black *which is done in both the RGB and RGBA formats*. The GL_LINEAR flag will work fine whether the internal format has an alpha channel or not.

The only reason the spec mentions for the RGB format, is to be compatible with itself:

    (4) A pre-compressed image with a DXT1 format can be used as either an
        RGB_S3TC_DXT1 or an RGBA_S3TC_DXT1 image.  If the image has
        transparent texels, how are they treated in each format?

        RESOLVED:  The renderer has to make sure that an RGB_S3TC_DXT1 format
        is decoded as RGB (where alpha is effectively one for all texels),
        while RGBA_S3TC_DXT1 is decoded as RGBA (where alpha is zero for all
        texels with "transparent" encodings).  Otherwise, the formats are
        identical.

So because OpenGL specifies a format that violates the MSDN spec we have to ensure that we use this incompatible format without any way to detect it from the DDS header. We should save developers the hassle and not support a format that violates the MSDN specification only to be compatible with itself. Because in the end the DDS format is specified by MSDN and not by OpenGL.

### So when should the RGB format of DXT1 be used?

The only reason to ever use the RGB format is when you are *not* loading a DDS file and you are instead loading a file format that does explicitly specify textures that were encoded by the OpenGL RGB enum. So clearly this is a format that is not compatible with DirectX.

### CODE REVIEW

**Comment by Armada651** [comment]
@Groovounet I've found the correct fix, the RGB enum should be specified as an unknown format for DirectX as it is OpenGL-specific. I've added plenty of information in the description to support my claim.

**Comment by Armada651** [comment]
@Groovounet Also, please don't take my obsession with this issue personally. I think GLI is a great library, which is why I don't want a misinterpretation of the spec to be part of it.

I'd even suggest reverting the part of bb4dd6082d6514d3afa32678163b9ce86ec3577b that takes the flags into account. Because your previous interpretation was correct, if there is a format that has an alpha and a non-alpha variant then DirectX specifies that explicitly in the format without relying on flags.

**Comment by Armada651** [comment]
@Groovounet Could you review this PR? You currently have the Alpha Pixels flag specified for texture formats without alpha channels.

**Comment by Groovounet** [comment]
I still think that the DDPF_ALPHAPIXELS  topic needs more work than that but the propose changes seem reasonable. 

By the way, what's on MSDN isn't a spec it's at best a documentation. The problem with DDS is that it never been specified and many tools tried to figure out how it's supposed to work plus Microsoft made DDS evolve multiple time. 

So the reality of making a DDS loader is also to take into account how existing tools behave to ensure interoperability.

Thanks for digging into this, I'll certainly use it later to improve GLI DDS support coverage.

**Comment by Armada651** [comment]
@Groovounet I realize that the MSDN documentation is at best a recommendation. But since they are pretty much the authoritative source regarding DDS it's the best we have since I haven't seen a real spec anywhere. Even the OpenGL spec often refers to the MSDN documentation.

**Comment by Groovounet** [comment]
"Even the OpenGL spec often refers to the MSDN documentation" eum where?

**Comment by Groovounet** [comment]
I think the proper way to resolve the issue is using the DDS_ALPHA_MODE. 

https://msdn.microsoft.com/en-us/library/windows/desktop/bb943983(v=vs.85).aspx

But "Note  The legacy D3DX 10 and D3DX 11 utility libraries will fail to load any .DDS file with miscFlags2 not equal to zero." sounds scary.

**Pull request merged**
